# Generated by Django 2.0.7 on 2020-05-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_target_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.Post', verbose_name='评论对象'),
        ),
    ]
